Update buildspec.yml

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -1,42 +1,18 @@
-# version: 0.2
-
-# phases:
-#   install:
-#     runtime-versions:
-#       python: 3.10
-#     commands:
-#       - mkdir terraform
-#       - cd terraform
-#       - if [ ! -x "$(command -v terraform)" ]; then
-#           echo Installing Terraform;
-#           curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/1.1.4/terraform_1.1.4_linux_amd64.zip;
-#           unzip -o /tmp/terraform.zip -d /usr/local/bin/;
-#         fi
-#       - terraform -version
-#   build:
-#     commands:
-#       - echo Building Infrastructure with Terraform
-# #       - cd terraform
-#       - terraform init
-#       - terraform validate
-#       - terraform plan -out=tfplan || echo "terraform plan failed"
-#       - terraform show -json tfplan > tfplan.json || echo "terraform show failed"
-#   post_build:
-#     commands:
-#       - echo Deploying Infrastructure with Terraform
-# #       - cd terraform
-#       - terraform plan -detailed-exitcode -out=tfplan || PLAN_EXIT_CODE=$?
-#       - if [ $PLAN_EXIT_CODE -eq 2 ]; then terraform apply -auto-approve tfplan; fi
 version: 0.2
 
 phases:
   install:
+    runtime-versions:
+      python: 3.10
     commands:
-      - apt-get update
-      - apt-get install -y curl
-      - curl -O https://releases.hashicorp.com/terraform/1.0.10/terraform_1.0.10_linux_amd64.zip
-      - unzip terraform_1.0.10_linux_amd64.zip
-      - mv terraform /usr/local/bin/
+      - mkdir terraform
+      - cd terraform
+      - if [ ! -x "$(command -v terraform)" ]; then
+          echo Installing Terraform;
+          curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/1.1.4/terraform_1.1.4_linux_amd64.zip;
+          unzip -o /tmp/terraform.zip -d /usr/local/bin/;
+        fi
+      - terraform -version
   build:
     commands:
       - echo Building Infrastructure with Terraform
@@ -51,4 +27,28 @@ phases:
 #       - cd terraform
       - terraform plan -detailed-exitcode -out=tfplan || PLAN_EXIT_CODE=$?
       - if [ $PLAN_EXIT_CODE -eq 2 ]; then terraform apply -auto-approve tfplan; fi
+# version: 0.2
+
+# phases:
+#   install:
+#     commands:
+#       - apt-get update
+#       - apt-get install -y curl
+#       - curl -O https://releases.hashicorp.com/terraform/1.0.10/terraform_1.0.10_linux_amd64.zip
+#       - unzip terraform_1.0.10_linux_amd64.zip
+#       - mv terraform /usr/local/bin/
+#   build:
+#     commands:
+#       - echo Building Infrastructure with Terraform
+# #       - cd terraform
+#       - terraform init
+#       - terraform validate
+#       - terraform plan -out=tfplan || echo "terraform plan failed"
+#       - terraform show -json tfplan > tfplan.json || echo "terraform show failed"
+#   post_build:
+#     commands:
+#       - echo Deploying Infrastructure with Terraform
+# #       - cd terraform
+#       - terraform plan -detailed-exitcode -out=tfplan || PLAN_EXIT_CODE=$?
+#       - if [ $PLAN_EXIT_CODE -eq 2 ]; then terraform apply -auto-approve tfplan; fi
 
